#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.36.0
# Product:       sgp43
# Model-Version: 2.1.0
#

import pytest
from sensirion_i2c_sgp43.device import Sgp43Device


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 3.3
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x59,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Sgp43Device(channel)


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_execute_self_test1(sensor):
    test_result = sensor.execute_self_test()
    print(f"test_result: {test_result}; "
          )


def test_execute_conditioning1(sensor):
    sraw_voc = sensor.execute_conditioning(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          )
    sraw_voc = sensor.execute_conditioning(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          )
    (sraw_voc, sraw_nox
     ) = sensor.measure_raw_signals(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          f"sraw_nox: {sraw_nox}; "
          )
    sraw_voc = sensor.execute_conditioning(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          )
    (a_sraw, a_sraw_1, a_sraw_2, a_sraw_3
     ) = sensor.measure_set_multipixel_temperature(120)
    print(f"a_sraw: {a_sraw}; "
          f"a_sraw_1: {a_sraw_1}; "
          f"a_sraw_2: {a_sraw_2}; "
          f"a_sraw_3: {a_sraw_3}; "
          )
    (sraw_voc, sraw_nox
     ) = sensor.measure_raw_signals(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          f"sraw_nox: {sraw_nox}; "
          )
    (sraw_voc, sraw_nox
     ) = sensor.measure_raw_signals(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          f"sraw_nox: {sraw_nox}; "
          )
    sensor.turn_heater_off()

