#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.4.2
# Product:       sgp43
# Model-Version: 3.1.0
#

import pytest
from sensirion_i2c_sgp43.device import Sgp43Device


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 3.3
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x59,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Sgp43Device(channel)


def test_turn_heater_off1(sensor):
    sensor.turn_heater_off()


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_execute_self_test1(sensor):
    test_result = sensor.execute_self_test()
    print(f"test_result: {test_result}; "
          )


def test_measure_and_set_temperatures1(sensor):
    (sraw_px1, sraw_px2, sraw_px3, sraw_px4
     ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
    print(f"sraw_px1: {sraw_px1}; "
          f"sraw_px2: {sraw_px2}; "
          f"sraw_px3: {sraw_px3}; "
          f"sraw_px4: {sraw_px4}; "
          )
    (sraw_px1, sraw_px2, sraw_px3, sraw_px4
     ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
    print(f"sraw_px1: {sraw_px1}; "
          f"sraw_px2: {sraw_px2}; "
          f"sraw_px3: {sraw_px3}; "
          f"sraw_px4: {sraw_px4}; "
          )
    test_result = sensor.execute_self_test()
    print(f"test_result: {test_result}; "
          )
    sensor.turn_heater_off()

