#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.3.4
# Product:       sgp43
# Model-Version: 3.0.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sgp43.device import Sgp43Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x59,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sgp43Device(channel)
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    (sraw_px1, sraw_px2, sraw_px3, sraw_px4
     ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
    print(f"sraw_px1: {sraw_px1}; "
          f"sraw_px2: {sraw_px2}; "
          f"sraw_px3: {sraw_px3}; "
          f"sraw_px4: {sraw_px4}; "
          )
    for i in range(50):
        try:
            time.sleep(1.0)
            (sraw_px1, sraw_px2, sraw_px3, sraw_px4
             ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
            print(f"sraw_px1: {sraw_px1}; "
                  f"sraw_px2: {sraw_px2}; "
                  f"sraw_px3: {sraw_px3}; "
                  f"sraw_px4: {sraw_px4}; "
                  )
        except BaseException:
            continue
    sensor.turn_heater_off()
