#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.36.0
# Product:       sgp43
# Model-Version: 2.1.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sgp43.device import Sgp43Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x59,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sgp43Device(channel)
    try:
        sensor.turn_heater_off()
        time.sleep(0.1)
    except BaseException:
        ...
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    sraw_voc = sensor.execute_conditioning(32768, 26214)
    print(f"sraw_voc: {sraw_voc}; "
          )
    for i in range(50):
        try:
            (sraw_voc, sraw_nox
             ) = sensor.measure_raw_signals(32768, 26214)
            print(f"sraw_voc: {sraw_voc}; "
                  f"sraw_nox: {sraw_nox}; "
                  )
        except BaseException:
            continue
    sensor.turn_heater_off()
