#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.6.0
# Product:       sgp43
# Model-Version: 3.2.0
#

import argparse
import time
from sensirion_i2c_driver import I2cConnection, CrcCalculator
from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import (SensorBridgePort,
                                          SensorBridgeShdlcDevice,
                                          SensorBridgeI2cProxy)
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sgp43.device import Sgp43Device

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM1')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=460800) as port:
    bridge = SensorBridgeShdlcDevice(ShdlcConnection(port), slave_address=0)
    bridge.set_i2c_frequency(SensorBridgePort.ONE, frequency=100e3)
    bridge.set_supply_voltage(SensorBridgePort.ONE, voltage=3.3)
    bridge.switch_supply_on(SensorBridgePort.ONE)
    i2c_transceiver = SensorBridgeI2cProxy(bridge, port=SensorBridgePort.ONE)
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x59,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sgp43Device(channel)
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    (sraw_px1, sraw_px2, sraw_px3, sraw_px4
     ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
    print(f"sraw_px1: {sraw_px1}; "
          f"sraw_px2: {sraw_px2}; "
          f"sraw_px3: {sraw_px3}; "
          f"sraw_px4: {sraw_px4}; "
          )
    for i in range(50):
        try:
            time.sleep(1.0)
            (sraw_px1, sraw_px2, sraw_px3, sraw_px4
             ) = sensor.measure_and_set_temperatures(400, 200, 350, 350)
            print(f"sraw_px1: {sraw_px1}; "
                  f"sraw_px2: {sraw_px2}; "
                  f"sraw_px3: {sraw_px3}; "
                  f"sraw_px4: {sraw_px4}; "
                  )
        except BaseException:
            continue
    sensor.turn_heater_off()
